export const UserData = [
    {
        id:1,
        name:"adhavan",
        role_no:458454,
        tamil:56,
        english:88,
        maths:89,
    },
    {
        id:2,
        name:"infanta",
        role_no:458415,
        tamil:56,
        english:88,
        maths:89,
    },
    {
        id:3,
        name:"kumar",
        role_no:458411,
        tamil:56,
        english:88,
        maths:89,
    }
]